using MultiplayerARPG;
using MultiplayerARPG.Server.AI;
using MultiplayerARPG.Server.Scheduling;

namespace MultiplayerARPG.Server.Runtime
{
    /// <summary>
    /// Applies movement intents generated by MonsterActivityAISystem.
    /// Kept conservative under pressure to avoid visible server rubberbanding.
    /// </summary>
    public sealed class MonsterActivityMoveIntentSystem : ITickSystem, ILoadSheddingTickSystem, IOrderedTickSystem
    {
        public string Name { get { return nameof(MonsterActivityMoveIntentSystem); } }
        public int Order { get { return 0; } }

        public bool ShouldRun(in TickContext ctx, SchedulerPressureLevel pressureLevel)
        {
            // Movement intent application is cheap and visible. Do not skip globally.
            return true;
        }

        public void Prepare(in TickContext ctx) { }

        public void Execute(in TickContext ctx)
        {
            var list = MonsterActivityTickRegistry.Snapshot();
            for (int i = 0; i < list.Count; i++)
            {
                var comp = list[i];
                if (comp == null || comp.Entity == null)
                    continue;

                var identity = comp.Entity.Identity;
                if (identity != null && identity.CountSubscribers() == 0)
                    continue;

                comp.TickMoveIntent(ctx.FixedDelta);
            }
        }

        public void Commit(in TickContext ctx) { }
    }
}
