using MultiplayerARPG;
using MultiplayerARPG.Server.AI;
using MultiplayerARPG.Server.Scheduling;

namespace MultiplayerARPG.Server.Runtime
{
    /// <summary>
    /// Applies combat intents generated by MonsterActivityAISystem.
    /// Combat remains authoritative and should not be globally skipped by load shedding.
    /// </summary>
    public sealed class MonsterActivityCombatSystem : ITickSystem, ILoadSheddingTickSystem, IOrderedTickSystem
    {
        public string Name { get { return nameof(MonsterActivityCombatSystem); } }
        public int Order { get { return 0; } }

        public bool ShouldRun(in TickContext ctx, SchedulerPressureLevel pressureLevel)
        {
            // Do not shed authoritative combat execution at the system level.
            return true;
        }

        public void Prepare(in TickContext ctx) { }

        public void Execute(in TickContext ctx)
        {
            var list = MonsterActivityTickRegistry.Snapshot();
            for (int i = 0; i < list.Count; i++)
            {
                var comp = list[i];
                if (comp == null || comp.Entity == null)
                    continue;

                var identity = comp.Entity.Identity;
                if (identity != null && identity.CountSubscribers() == 0)
                    continue;

                comp.TickCombat(ctx.FixedDelta);
            }
        }

        public void Commit(in TickContext ctx) { }
    }
}
